name: build
on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
      - main

env: # Change this if needed
  quarto_file: content
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  computorticle:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2
           
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt
      
      - name: Installing quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Rendering with Quarto
        shell: bash -l {0}
        run: |
            quarto render ${{ env.quarto_file }}.qmd
            mkdir _build
            mv ${{ env.quarto_file }}.html _build/index.html
            mv -vf ${{ env.quarto_file }}_files figures ${{ env.quarto_file }}.pdf _build/
            cp requirements.txt _build/
            touch _build/.nojekyll

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
